flags: {}
packages:
- '.'
- '../gl-pal'
- '../glfw-pal'
- '../game-pal'
- '../halive'
- '../hydra-hs'
- '../oculus-mini'
- '../linear-extra'
- '../lens-extra'
extra-deps:
- GLFW-b-1.4.7.3
- bindings-GLFW-3.1.1.4
resolver: lts-3.0
