flags: {}
packages:
- '.'
- '../gl-pal'
- '../glfw-pal'
- '../game-pal'
- '../halive'
- '../hydra-hs'
- '../oculus-mini'
- '../linear-extra'
- '../lens-extra'
- '../openvr-hs'
extra-deps:
- GLFW-b-1.4.7.3
- bindings-GLFW-3.1.1.4
- inline-c-0.5.5.1
- inline-c-cpp-0.1.0.0
resolver: lts-3.0
